version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-library
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_USER: book_user
      MYSQL_PASSWORD: book_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app-network

  app:
    build: .
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library_db
      SPRING_DATASOURCE_USERNAME: book_user
      SPRING_DATASOURCE_PASSWORD: book_pass
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
